# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nj0vibUKaOUcf0fd1ugwzDAFKsGyLTTO
"""

import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

my_data = pd.read_csv("/content/drive/MyDrive/Iris.csv", delimiter=",")
my_data[0:5]
my_data.head()

from google.colab import drive
drive.mount('/content/drive')



my_data.head()

my_data.shape

X = my_data[['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values
X[0:5]

y = my_data["Species"]
y[0:5]

from sklearn.model_selection import train_test_split

X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

X_trainset.shape

X_testset.shape

y_trainset.shape

y_testset.shape

irisTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
irisTree # it shows the default parameters

irisTree.fit(X_trainset,y_trainset)

predTree = irisTree.predict(X_testset)

print (predTree [0:5])

print (y_testset [0:5])

from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

# Commented out IPython magic to ensure Python compatibility.
from  io import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn import tree
# %matplotlib inline

dot_data = StringIO()
filename = "iristree.png"
featureNames = my_data.columns[0:5]
out=tree.export_graphviz(irisTree,feature_names=featureNames, out_file=dot_data, class_names= np.unique(y_trainset), filled=True,  special_characters=True,rotate=False)  
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png(filename)
img = mpimg.imread(filename)
plt.figure(figsize=(100, 200))
plt.imshow(img,interpolation='nearest')